### ISSUE TITLE
generate on branching added extra image: field on jobs pointing to master

### ISSUE THREAD

**Issue by ericvn** [sebastienvas/istio-testing#3792]
This image overrides the image being updated to the release at the top of each file.

**Comment by ericvn** [comment]
Still exists for the 1.14 branching.

**Comment by ericvn** [comment]
Example:
```
- name: BUILD_WITH_CONTAINER
  value: "0"
image: gcr.io/istio-testing/build-tools:release-1.16-6363b97c6bc60b7a3a8d52c5e08322d8394149e2
jobs:
- command:
  - make
  - build
  env:
  - name: BUILD_WITH_CONTAINER
    value: "0"
  - name: BUILD_WITH_CONTAINER
    value: "0"
  image: gcr.io/istio-testing/build-tools:master-6363b97c6bc60b7a3a8d52c5e08322d8394149e2
```
You can see the overall `master was updated to `1.16`, but the individual jobs still have `master`.
